version: '3.3'
services:
    dnsmasq:
        container_name: dnsmasq
        build: .
        ports:
            - '53:53/udp'
            - '5380:8080'
        volumes:
            - '/opt/dnsmasq.conf:/etc/dnsmasq.conf'
        logging:
            options:
                max-size: 100m
        environment:
            - HTTP_USER=foo
            - HTTP_PASS=bar
        restart: always
        cap_add:
            - 'NET_ADMIN'
     
